[build]
  base = "javascript"
  command = "npm run build-examples"
  publish = "example/bundle"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/mujoco/*"
  to = "/mujoco/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

